name: carman
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.19.0
  flutter_timezone: ^2.0.1
  provider: ^5.0.0
  timezone: ^0.9.3
  flutter_local_notifications: ^17.2.1+1
  page_transition: ^2.1.0
  curved_navigation_bar: ^1.0.6
  flutter_localization: ^0.2.0
  flutter_speed_dial: ^7.0.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  camera_camera: ^3.0.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

 
